"""add_image_hash_to_rewards_and_reels

Revision ID: 44f1af140c82
Revises: 2a4b5c6d7e8f
Create Date: 2026-01-05 16:01:21.152418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '44f1af140c82'
down_revision: Union[str, Sequence[str], None] = '2a4b5c6d7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'mrp')
    op.create_index(op.f('ix_qr_batches_id'), 'qr_batches', ['id'], unique=False)
    op.add_column('reels', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_reels_image_hash'), 'reels', ['image_hash'], unique=True)
    op.add_column('rewards', sa.Column('image_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_rewards_coupon_code'), 'rewards', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_rewards_image_hash'), 'rewards', ['image_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_image_hash'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_coupon_code'), table_name='rewards')
    op.drop_column('rewards', 'image_hash')
    op.drop_index(op.f('ix_reels_image_hash'), table_name='reels')
    op.drop_column('reels', 'image_hash')
    op.drop_index(op.f('ix_qr_batches_id'), table_name='qr_batches')
    op.add_column('products', sa.Column('mrp', mysql.FLOAT(), nullable=False))
    op.add_column('products', sa.Column('selling_price', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
